name: client
description: client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  vrouter: ^1.2.1
  google_fonts: ^3.0.1
  graphql_flutter: ^5.1.0
  dio: ^4.0.6
  transparent_image: ^2.0.0
  json_serializable: ^6.2.0
  flutter_hooks: ^0.18.3
  provider: ^6.0.3
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  flutter_image_slideshow: ^0.1.2
  enum_to_string: ^2.0.1
  charts_flutter: ^0.12.0
  awesome_dialog: ^2.2.1
  file_picker: ^4.6.1
  loading_indicator: ^3.0.3
  carousel_slider: ^4.1.1
  timeago: ^3.2.2
  bubble: ^1.2.1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  lottie: ^1.3.0
  flutter_barcode_scanner: ^2.0.0
  better_player: ^0.0.82
  url_launcher: ^6.1.3
  percent_indicator: ^4.2.1
  card_swiper: ^2.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: '^0.11.0'
  flutter_native_splash: ^2.1.1
  flutter_dotenv: ^5.0.2
  graphql_codegen: ^0.9.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.pntransparent_image: ^2.0.0g
    - assets/avatar/
    - assets/avatar/body/
    - assets/avatar/head/
    - assets/avatar/accessory/
    - assets/images/auth/
    - assets/images/login/
    - assets/images/register/
    - assets/images/register-profile/
    - assets/lottie/
    - assets/icons/
    - .env

flutter_icons:
  image_path: 'assets/logo.png'
  adaptive_icon_foreground: 'assets/logo.png'
  adaptive_icon_background: '#7C4DFF'
  ios: true
  android: true
  web:
    generate: true

flutter_native_splash:
  color: '#7C4DFF'
  image: 'assets/logo-min.png'

  android_12:
    image: assets/logo.png
